- release-notes.en.md
- release-notes.md
* Fixed bug that metadata on Media/DataConnection class was not set.
* Updated some comments on header files.
> Update to v1.0.1

- .github/ISSUE_TEMPLATE.md
* Add an issue template which is added automatically when someone creates new issue
* Add a note about SkyWay developer community forums
> add GItHub issue template

- examples/README.md
[Fix points]
* Learn more Link
* Add the item 'how to build'
> Fix README.md of example

- examples/mesh-videochat/app/src/main/res/layout/view_remote.xml
- examples/sfu-videochat/app/src/main/res/layout/view_remote.xml
- Update  view_remote sfu-videochat and mesh-videochat examples
- Add `layout_constraintDimensionRatio`
> Update view_remote for sfu-videochat and mesh-videochat exampls

- README.md
Fix #34  
I fix tutorial link in README.
> fix tutorial link

- examples/mesh-textchat/app/src/main/java/com/ntt/ecl/webrtc/sample_mesh_textchat/MainActivity.java
- examples/mesh-videochat/app/src/main/java/com/ntt/ecl/webrtc/sample_mesh_videochat/MainActivity.java
- examples/p2p-call/app/src/main/java/com/ntt/ecl/webrtc/sample_p2p_call/MainActivity.java
- examples/p2p-textchat/app/src/main/java/com/ntt/ecl/webrtc/sample_p2p_textchat/MainActivity.java
- examples/p2p-videochat/app/src/main/java/com/ntt/ecl/webrtc/sample_p2p_videochat/MainActivity.java
- examples/sfu-textchat/app/src/main/java/com/ntt/ecl/webrtc/sample_sfu_textchat/MainActivity.java
- examples/sfu-videochat/app/src/main/java/com/ntt/ecl/webrtc/sample_sfu_videochat/MainActivity.java
Getting error messages by using error.getMessage instead of error.message
> Change getting error message method

- release-notes.en.md
- release-notes.md
> [DO NOT MERGE]  Skyway/v2.0.1

- release-notes.en.md
- release-notes.md
> Release v2.0.3

- release-notes.en.md
- release-notes.md
Fixed a bug in which the ICE Connection was disconnecting when the ICE Connection was temporarily disconnected due to communication instability and other reasons, even though there was a possibility of reconnecting.
> Release v2.0.4

- release-notes.en.md
- release-notes.md
- Corrected wording in the release notes for  v2.0.4.
> Corrected wording in the release notes.

- release-notes.en.md
- release-notes.md
Add release date to release notes.
> Add release date

- release-notes.en.md
- release-notes.md
Update release notes for v2.3.0.
> Update release-notes for v2.3.0

- examples/mesh-textchat/app/src/main/java/com/ntt/ecl/webrtc/sample_mesh_textchat/MainActivity.java
- examples/mesh-videochat/app/src/main/java/com/ntt/ecl/webrtc/sample_mesh_videochat/MainActivity.java
- examples/sfu-textchat/app/src/main/java/com/ntt/ecl/webrtc/sample_sfu_textchat/MainActivity.java
- examples/sfu-videochat/app/src/main/java/com/ntt/ecl/webrtc/sample_sfu_videochat/MainActivity.java
Deprecated room's REMOVE_STREAM event
> Deprecated room's REMOVE_STREAM event

- examples/mesh-textchat/app/src/main/java/com/ntt/ecl/webrtc/sample_mesh_textchat/MainActivity.java
- examples/mesh-videochat/app/src/main/java/com/ntt/ecl/webrtc/sample_mesh_videochat/MainActivity.java
- examples/p2p-call/app/src/main/java/com/ntt/ecl/webrtc/sample_p2p_call/MainActivity.java
- examples/p2p-textchat/app/src/main/java/com/ntt/ecl/webrtc/sample_p2p_textchat/MainActivity.java
- examples/p2p-videochat/app/src/main/java/com/ntt/ecl/webrtc/sample_p2p_videochat/MainActivity.java
- examples/sfu-textchat/app/src/main/java/com/ntt/ecl/webrtc/sample_sfu_textchat/MainActivity.java
- examples/sfu-videochat/app/src/main/java/com/ntt/ecl/webrtc/sample_sfu_videochat/MainActivity.java
Stop using peer's DISCONNECTED event and disconnect()
> Stop using peer's DISCONNECTED event and disconnect() in examples

- release-notes.en.md
- release-notes.md
> Release v2.6.0

- release-notes.en.md
- release-notes.md
> Release v3.0.0

- release-notes.en.md
- release-notes.md
> Release v3.0.1

- release-notes.en.md
- release-notes.md
- Added SNI information to the request header when sending a request to the server.
> Release v3.1.0

- release-notes.en.md
- release-notes.md
Fixed a bug that could cause the application to crash after disconnecting the connection.
> Update release notes for v3.1.1

- release-notes.en.md
- release-notes.md
- Updated internal WebRTC libraries to improve stability
> Release v4.0.0

- release-notes.en.md
- release-notes.md
- Fixed a bug that `Canvas.ScalingEnum.ASPECT_FIT` does not work properly
> Release v4.0.1

- release-notes.en.md
- release-notes.md
New SkyWay and old SkyWay can be used in one app.
> Release v4.0.2

- release-notes.en.md
- release-notes.md
> Release v4.0.3

- release-notes.en.md
- release-notes.md
> [4.0.4]update v4.0.4 release note

- release-notes.en.md
- release-notes.md
> [4.0.5]update v4.0.5 release note
